name: Jekyll Site CI

on:
  push:
    branches:
      - main  # Replace with the branch you're using for GitHub Pages (e.g., gh-pages)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify your Ruby version if needed (you can use '2.7' or another version if required)

    - name: Install Jekyll and dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # Specify the branch to publish to (use gh-pages if this is your deployment branch)
        publish_dir: ./_site  # Default output directory for Jekyll

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
